### PR TITLE
Remove failing docker publish line

### PR DESCRIPTION
**Pull request by MSevey**
## Overview
The docker workflow had a duplicate build and push step that was causing the CI to fail.

This should be applied/verified on rollkit and we should bump the version. 

This should close https://github.com/celestiaorg/devops/issues/326

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

### CODE REVIEW

**Review by adlerjohn — APPROVED** [review]
utACK

**Comment by rootulp** [comment]
@MSevey does this close https://github.com/celestiaorg/devops/issues/326 ?

**Review by rootulp — APPROVED** [review]

**Comment by MSevey** [comment]
> @MSevey does this close [celestiaorg/devops#326](https://github.com/celestiaorg/devops/issues/326) ?

yes I think it should. good catch

**Review by Bidon15 — APPROVED** [review]
We will be building images slow again with this PR. 

I'll do a very dirty PR next time to avoid slow time due to linux/arm64

cc: @celestiaorg/devops

**Pull request merged**
